### PR TITLE
welcome event.

### PR DESCRIPTION
**Pull request by ronyrun**
a welcome event.

### CODE REVIEW

**Comment by colinskow** [comment]
I'm not sure what the purpose of the welcome event is?

**Comment by ronyrun** [comment]
Hi,

The purpose is to give log and pwd to users through mail or other solution.
This way they can have it if they forgot.

**Comment by colinskow** [comment]
That is generally bad security to save or send out the password anywhere. If they forget their password they can use password reset.

**Comment by ronyrun** [comment]
ok

**Pull request closed without merging**
