### PR TITLE
Clarify adding additional fields

### PR DESCRIPTION
**Pull request by peteruithoven**
I found the information on adding additional (profile) fields somewhat spread out over the documentation and lacking some examples. This is a proposal to clarify this.

### CODE REVIEW

**Comment by colinskow** [comment]
@peteruithoven Thank you very much! I will likely merge this as-is. I've got some paid projects to finish and then I will be handling all the SuperLogin PRs to make a new release within the next few weeks.

**Comment by colinskow** [comment]
@peteruithoven I am about ready to merge this, but I have one question... Did you test these instructions yourself to verify that they work as expected?

**Comment by peteruithoven** [comment]
I wrote these while / after I figured this out myself and implemented it into a project I'm working on.

**Comment by colinskow** [comment]
Merged, thank you very much!

**Pull request merged**
