### PR TITLE
Adding new route to update custom fields

### PR DESCRIPTION
**Pull request by mriccia**
As mentioned in this issue https://github.com/colinskow/superlogin/issues/81
I was wondering if you plan to have an "update" on custom fields?

If so, please take a look at this PR and let me know what you think.

### CODE REVIEW

**Comment by colinskow** [comment]
Thank you for the PR! I'm working on some other paid projects and will be reviewing all the SuperLogin issues within the next few weeks to work on the next release.

**Comment by numerized** [comment]
:)))) nice one !

**Comment by jpmsegurado** [comment]
@colinskow can you take a look on this PR? I'm using the superlogin,  and right now this feature is very important. Thanks in advance.

**Comment by numerized** [comment]
🥇

**Comment by colinskow** [comment]
Sorry for the delay. My opinion is that each developer is going to want to use different logic about what changes are allowed. The `userModel.whitelist` was designed for new registrations, but I don't think it's flexible enough to handle updates. Developers may also want to update multiple fields at a time to conserve db requests.

`superlogin-demo` already has a [solution](https://github.com/colinskow/superlogin-demo/blob/master/server/profile.js #L41), which is to directly access the PouchDB `superlogin.userDB` and put the document manually.

I would support adding a helper function to the SuperLogin API to update a user, perhaps with some minimal validations, but not a route as this is easy to implement yourself with the specific logic of your app.

**Pull request closed without merging**
