### PR TITLE
Added file session adapter

### PR DESCRIPTION
**Pull request by micky2be**
For development purpose only, here a file adapter for sessions.
This will help to keep a persistent session on server reload (which happen a lot during development).

Note: I put all the adapters into a dedicated folder and took the liberty to change the code of them into prototype style to reduce the memory print.

---
This change is [Reviewable](https://reviewable.io/reviews/colinskow/superlogin/57)

### CODE REVIEW

**Comment by micky2be** [comment]
Weird it's failing with node 4.x but working with node 5.x

**Comment by micky2be** [comment]
Ok, looks like there was a bug with `path.format` in Node 4.x

**Comment by colinskow** [comment]
Thank you very much. I will definitely merge this in over the next few days as soon as I have a chance to check over the code.

**Comment by ronyrun** [comment]
Does this applied on Heroku ?
I thought Heroku was deleting every project files when Pushing and relaunching the process.

**Comment by colinskow** [comment]
Every time Heroku reboots your Dyno the file will be lost. With Heroku you need Redis. The file adapter is great for local testing though.

**Pull request merged**
