### PR TITLE
Allow custom password rules

### LINKED ISSUE #35: Option to set the password constraints
I would like to be able to choose myself what is mandatory for the password for my users.
Being stuck to "minimum 6 characters" is not ideal for the application I'm trying to build.

If it already exist please point me to the right direction.

### PR DESCRIPTION
**Pull request by micky2be**
With one setting, allow to set the rules for the password.

Closes #35

### CODE REVIEW

**Comment by colinskow** [comment]
Thank you very much. I think this is a good idea. It would be incredibly helpful if you could write a test to verify it works as expected under `user.spec.js`.

**Comment by micky2be** [comment]
Very sorry for the delay, got distracted by other projects.
I updated the test to reflect the changes.

**Comment by colinskow** [comment]
Thank you very much @micky2be ... You have been a huge help to this project!!!

**Comment by simonmcl** [comment]
Did this ever make it into a release? running `0.6.1` it doesn't seem to be working

**Pull request merged**
