### PR TITLE
Unit tests now have their own config, Replaced most done()/done(err) calls by returning promises.

### PR DESCRIPTION
**Pull request by tohagan**
- Replaced almost all done()/done(err) calls in tests by returning promises to Mocha.

### Applied patch from ybain's fork:
- Fix tests to support non admin party CouchDb 
- Added test.conf.js to configure unit tests (patch from ybain's fork).
- tohagan added environment vars for CouchDb server config.
- Now test server uses port 5000 by default (ybain and I both hit a conflict on port 4000).

I needed ybain's patch to make unit tests work.

### CODE REVIEW

**Comment by tohagan** [comment]
Travis will need the following env vars setup to build:

	COUCH_HOST=localhost:5984
	COUCH_USER=?????
	COUCH_PASS=????
	CLOUDANT_USER=????
	CLOUDANT_PASS=????
	FROM_EMAIL=noreply@example.org
	SENDGRID_USERNAME=????
	SENDGRID_PASSWORD=????
	FACEBOOK_CLIENTID=????
	FACEBOOK_CLIENTSECRET=????

**Comment by colinskow** [comment]
@tohagan Thank you very much for the PR! I will be working on a new release over the next couple weeks and will be handling all pull requests then.

**Comment by colinskow** [comment]
Hi @tohagan I'm working on merging this, but it is a bit messy with 6 commits. Please squash and rebase with the current master.

**Comment by tohagan** [comment]
I'm sorry about this all commits. They were interdependent and the 1st one case a patch from another git user required to get my local test environment to work.  I also tried to document what each change was doing.

**Comment by tohagan** [comment]
Just wasted another day trying to get all these patches applied.

**Pull request closed without merging**
